using SkyrimShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SkyrimShop.DAL
{
    public class ItemInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<ItemContext>
    {
        protected override void Seed(ItemContext context)
        {
            var items = new List<Item>
            {
            new Item{ItemName="Alessandra's Dagger", ItemType="Dagger",ItemPrice=10.00M,ItemDescription="Alessandra's Dagger is owned by Alessandra of Riften. It belonged to Alessandra's father and it was given to her when she was training to become a priestess of Arkay. After completing the training, she received a new ceremonial dagger and now she wishes to return the old one to her father's corpse in the Hall of the Dead in Whiterun, as a way of making peace.",ItemID=1,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Blade of Woe", ItemType="Dagger",ItemPrice=880.00M,ItemDescription="Higher attribute-wise than the Daedric Dagger, the Blade of Woe is exceptionally strong. With a Smithing skill of 100, it is possible for the dagger to reach a damage upwards of 60. Combined with the Assassin's Blade perk and Shrouded Hand Wraps, Shrouded Gloves, Ancient Shrouded Gloves , or Jester's Gloves, sneak attacks can reach 1,800+ damage. With Fortify Smithing, it is possible to obtain a base damage upwards of 115. Combined with the other bonuses mentioned above, sneak attacks can reach 2,700+ damage.The daggers enchantment has only six base charges. The amount of charge consumed by striking with the dagger lowers as Destruction level increases, assisting magic-based classes. It is actually possible to make the weapon use no charges by equipping four items with a 25% Fortify Destruction effect for a total of 100% reduction (this also works with many other enchantments).The enchantment is very weak compared to the potential of one crafted by the Dragonborn. With an Enchanting skill of 100, without using potions that have the Fortify Enchanting effect, an Absorb Health enchantment can do up to 20 damage and have many more charges available.",ItemID=2,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Blade of Sacrifice", ItemType="Dagger",ItemPrice=144.00M,ItemDescription="The Blade of Sacrifice can be found at the Sacellum of Boethiah, carried by the worshippers of Boethiah. One can be obtained during the quest Boethiah's Calling. Once the quest has been started, the Dragonborn is ordered to use it to sacrifice a follower at the Pillar of Sacrifice. More can be obtained from the other cultists, either from their corpses or through pickpocketing. When one first enters the Sacellum of Boethiah, there will be two cultists fighting. The one that dies has a Blade of Sacrifice. When sacrificing, it automatically kills the sacrifice",ItemID=3,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Bloodthorn", ItemType="Dagger",ItemPrice=183.00M,ItemDescription="Bloodthorn can be found on an altar on the balcony of Hag's End.",ItemID=4,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Borvir's Dagger",ItemType="Dagger",ItemPrice=18.00M,ItemDescription="Borvir's Dagger can be found near Borvir's corpse in Journeyman's Nook.",ItemID=6,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Daedric Dagger",ItemType="Dagger",ItemPrice=500.00M,ItemDescription="Similar to the sword, this dagger has a serrated edge. It also has the curved handle unique to Daedric weapons. Unenchanted Daedric Daggers will begin to appear throughout Skyrim at level 46 and enchanted daggers can be found at level 47, albeit very rarely.",ItemID=7,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dragonbone Dagger",ItemType="Dagger",ItemPrice=600.00M,ItemDescription="The Dragonbone dagger can swing much faster than most other Dragonbone weapons with just slightly less damage, making it a good choice for most builds, even non-thief ones. It is tied with the Blade of Woe for the dagger with the highest damage in the game, minus the Blade of Woe's enchantment. It, however, is much faster than the Blade of Woe, allowing for more damage per second.",ItemID=8,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dragon Priest Dagger",ItemType="Dagger",ItemPrice=9.00M,ItemDescription="The Dragon Priest Dagger is relatively rare, but can occasionally be found in ancient Nordic Tombs as a radiant item.",ItemID=9,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dwarven Dagger",ItemType="Dagger",ItemPrice=55.00M,ItemDescription="Compare and contrast a sharp, angular dwarven dagger to a curved elven blade, and it becomes a small logical leap to say that dwarven weaponsmiths relied almost exclusively on creating quality materials first, and merely allowed the form of those materials to flow from the method that weapon was intended to kill people.",ItemID=10,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Ebony Dagger",ItemType="Dagger",ItemPrice=290.00M,ItemDescription="Unenchanted Ebony Daggers will begin to appear throughout Skyrim at level 35, and enchanted daggers may be found at level 37.",ItemID=11,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Elven Dagger",ItemType="Dagger",ItemPrice=95.00M,ItemDescription="Unenchanted Elven daggers will begin to appear throughout Skyrim at level 19 and enchanted daggers can be found at level 20. It can be upgraded with a refined moonstone ingot at a grindstone. The Elven Smithing perk doubles the improvement. It can be upgraded with a refined malachite ingot at a grindstone and also benefits from the Glass Smithing perk, which doubles the improvement.",ItemID=12,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Glass Dagger",ItemType="Dagger",ItemPrice=165.00M,ItemDescription="Unenchanted glass daggers will begin to appear throughout Skyrim as early as level 25 and enchanted daggers can be found at level 28. ",ItemID=13,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Iron Dagger",ItemType="Dagger",ItemPrice=10.00M,ItemDescription="The Iron Dagger is a One-Handed weapon that appears in The Elder Scrolls V: Skyrim. It is one of the most common weapons available throughout Skyrim , and among the first weapons the to which the Dragonborn has access to. The vast majority of Skyrim's civilian population wield iron daggers.",ItemID=14,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Kahvozein's Fang",ItemType="Dagger",ItemPrice=9.00M,ItemDescription="It was named after the dragon that was worshipped by a particular sect of the dragon cult. According to Tolfdir, this sect was quite fond of ritual sacrifices, to the extent that the High Priest would spend a great deal of time sharpening the dagger so it was always ready for its next victim.",ItemID=15,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Keening",ItemType="Dagger",ItemPrice=5111.00M,ItemDescription="Keening is a unique ancient Dwemer dagger found in The Elder Scrolls V: Skyrim. It was crafted by Lord Kagrenac, Chief Tonal Architect of the Dwemer, during the First Era. He developed two additional tools, Sunder and Wraithguard, which were integral to accessing and harvesting the power from the Heart of Lorkhan buried under Red Mountain.",ItemID=16,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Mehrunes' Razor",ItemType="Dagger",ItemPrice=860.00M,ItemDescription="Mehrunes' Razor, also known as The Dagger of the Final Wounds, Bane of the Righteous and Kingslayer [1], is a Daedric artifact found in The Elder Scrolls V: Skyrim. It is a small black and silver dagger with the Daedric character for the letter O, Daedric O, engraved halfway along the scabbard. The unique enchantment grants the bearer a 1.98% [note 1] chance to instantly kill any opponent. The Razor has infinite charges, meaning it will never require recharging with a soul gem. (I am pleased, mortal. I will give you my Razor. Use it to wreak havoc on Tamriel. ―Mehrunes Dagon)",ItemID=17,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Nettlebane",ItemType="Dagger",ItemPrice=5.00M,ItemDescription="According to legend, Nettlebane is the only weapon old enough to cut through the bark of the Eldergleam Tree, since the tree is older than the existence of metal itself, and thus is unharmed by any other weapons. Danica Pure-Spring needs the sap from the Eldergleam to restore the Gildergreen Tree in the center of Whiterun's Wind District to its original glory.",ItemID=18,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Nordic Dagger",ItemType="Dagger",ItemPrice=115.00M,ItemDescription="Nordic Daggers can be created at a blacksmith's forge with the Advanced Armors. One can be found next to the body of Bjornolfr, behind the secret passage in Hrodulf's House. This is a fixed location and will spawn regardless of character level.",ItemID=19,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Orcish Dagger",ItemType="Dagger",ItemPrice=30.00M,ItemDescription="Unenchanted Orcish Daggers will begin to appear throughout Skyrim at level 6, and enchanted daggers can be found at level 7. Creating an Orcish dagger requires a Smithing level of 50, and the Orcish Smithing perk.",ItemID=20,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Rundi's Dagger",ItemType="Dagger",ItemPrice=18.00M,ItemDescription="Rundi's Dagger can be found at Rundi's Altar just southeast of The College of Winterhold. The dagger is sitting on the edge of the altar along with a soul gem, other items include Ice Wraith Teeth, Frostbite Venom, Frost Mirriam and the Alchemy skill book Mannimarco, King of Worms.",ItemID=21,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Shiv",ItemType="Dagger",ItemPrice=5.00M,ItemDescription="This particular Shiv appears to be a sharpened nail or piece of metal that is about five inches in length, with cloth or thin leather wrapped and tied around one end to serve as a grip on the handle. The Shiv is the fourth weakest weapon available, behind the fork, the Wooden sword, and the knife. It is classed as a dagger and thus is affected by the Assassin's Blade perk from the Sneak skill tree.",ItemID=22,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Skyforge Steel Dagger",ItemType="Dagger",ItemPrice=25.00M,ItemDescription=" This dagger, like all Skyforge Steel, is relatively rare as only a select few character in Skyrim carry it. It cannot be crafted and only one merchant, Eorlund Gray-Mane at the Skyforge, sells them. (Ah, the sneaky type, eh? I think we can fix you right up. ―Eorlund Gray-Mane, when asked for a Skyforge Steel Dagger)",ItemID=23,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Stalhrim Dagger",ItemType="Dagger",ItemPrice=395.00M,ItemDescription="A Stalhrim dagger requires a Smithing level of 80 and the Ebony Smithing perk to create. The quest A New Source of Stalhrim also needs to be completed. The Frost Damage enchantment is 25% stronger when placed on items crafted from Stalhrim. This effect is identical to the Frost Enchanter perk from the Enchanting skill tree, or the Augmented Frost perk from the Destruction skill tree.",ItemID=24,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Steel Dagger",ItemType="Dagger",ItemPrice=18.00M,ItemDescription="Crafting the dagger requires the Steel Smithing perk. Unenchanted Steel Daggers will begin to appear throughout Skyrim at level 2 and enchanted daggers can be found at level 3.",ItemID=26,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Valdr's Lucky Dagger",ItemType="Dagger",ItemPrice=15.00M,ItemDescription="Valdr's Lucky Dagger is owned by a Nord hunter named Valdr who received it as a gift from his good friend Ari. During a failed incursion into Moss Mother Cavern, Ari and their friend Niels were killed by a Spriggan, leaving Valdr wounded and unable to return home. During Hunter and Hunted, assisting Valdr in killing the remaining Spriggans in Moss Mother Cavern so that he may bury his friends will prompt him to bestow the dagger as a reward and a gift of thanks.(Ari gave me this dagger when we first started hunting together. Always said it brought her luck. You should be the one to carry it now.―Valdr)",ItemID=27,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Daedric Mace",ItemType="Mace",ItemPrice=1750.00M,ItemDescription="This mace is primarily black and gray in color. The overall finish is matte, with some gloss on the hammer marks and edges. Several rivets on the mace hold it together.Four serrated flanges curve in to form a crown at the tip of the mace. Red inlays are engraved into the flanges, they are faint in size and distinction, and emit a slight glow. On the central head of the mace there are four secondary flanges attached to the handle used as a support for the primary flanges, decorative engravings run down the length of these. The handle of the mace has two sections separated with a metal ring, each section has two parallel metal beams and three adjacent metal clasps. Brown leather strips are held down by the clasps and provide the grip for the handle. The handle has a metal ring on the bottom and continues to the pommel of the mace which has four small tertiary flanges in the form of spikes with a blunt exterior and bladed interior. They show visible warping from hammering during crafting.",ItemID=28,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dragonbone Mace",ItemType="Mace",ItemPrice=2000.00M,ItemDescription="One of the three Keepers in the Soul Cairn may wield a dragonbone mace, and if at a high enough level it can be taken from the body after its death. It is the most powerful mace, as well as the most powerful craftable one-handed weapon in the game.",ItemID=29,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dwarven Mace",ItemType="Mace",ItemPrice=190.00M,ItemDescription="The mace is gold, and brass in color, the over all lustre is dull under light, but there is a metallic shine to some parts of the head at certain angles. The head is one solid piece, following down the handle which has rivets to hold it together. Abrasions on the handle and head. A rectangular block of metal serves the center for the head of the mace, layering down at the top with some engravings at the very tip. Four hammer shaped flanges protrude from the flat surfaces of the block. At the bottom of the hammer flanges, secondary flanges in the shape of thin wings run down until the handle. Styled engravings are shown on the secondary flanges. Two parallel metal beams run the length of the handle, they are connected together as one piece by a small curved band of metal. Eleven adjacent metal clasps run down the handle. Worn brown leather serves as the grip. At the end of the handle a ring styled with engravings widens into the pommel which has a spherical protrusion.",ItemID=30,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Ebony Mace",ItemType="Mace",ItemPrice=1000.00M,ItemDescription="The mace is black and silver in color. Wear abrasions are visible on the styled linings and blade edges. The overall luster of the mace is sleek, the blades have a metallic sheen to them from sharpening. The head of the mace is composed of 8 bladed flanges. The flanges begin to come to a center point and then crown out, into individual edged tips. The central body of these flanges is styled in a decorative silver lining. The flanges are supported by the end of the rod. This area of the handle is decorated with floral silver linings.The shaft is partially smooth ebony, with the greater section of it being lined with stylized silver linings in geometric and curled patterns. The handle is wrapped with a strip of black leather several times over for a decent length of it. The pommel of the mace starts with an ebony metal ring, followed by an angled spike with a slight edge on the long side. This protrusion is styled with silver lining.",ItemID=31,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Elven Mace",ItemType="Mace",ItemPrice=330.00M,ItemDescription="The mace is brass in color, with some gold, white, and pearl. The overall luster of the mace is waxy, while the blades have a sub-metallic sheen to them. The mace shows abrasion and scratches.The mace's head has a shallow crown from the upper tips of the flanges. It has four flanges that start narrow at the top and widen towards the handle. The flanges hook over deeply, and come to a point facing inwards. The flanges consist of blades attached to metal coming together to the flat six sided blunt head. The handle starts with a shallow four edged rod, which narrows into the grip. The grip is made of brown leather, and a diagonal weave pattern of metal holding it to the body of the mace. The grip thins even more and then widens back out. The handle ends at the pommel which consists of two flared curve angled metal bars.",ItemID=32,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Glass Mace",ItemType="Mace",ItemPrice=572.00M,ItemDescription="Unenchanted Glass Maces will begin to appear throughout Skyrim at level 27, and enchanted maces can be found at level 28 (very rarely they can be found as early as level 11)",ItemID=33,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Horksbane",ItemType="Mace",ItemPrice=250.00M,ItemDescription="Horksbane is especially effective against horkers, dealing an extra 20 points of damage to them. This weapon may not be disenchanted, but new enchantments can be added to the weapon.",ItemID=34,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Iron Mace",ItemType="Mace",ItemPrice=35.00M,ItemDescription=" The Iron Mace is a One-Handed weapon and is one of the most common weapons available, being among the first to which the Dragonborn has access.",ItemID=35,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Lunar Iron Mace",ItemType="Mace",ItemPrice=168.00M,ItemDescription="As with all Lunar Weapons, the Lunar Iron Mace bears the Silent Moons Enchant. This unique enchantment burns the target for one second when struck.Lunar weapons are the only weapons that can be disenchanted to learn the Silent Moons Enchant.",ItemID=36,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Lunar Steel Mace",ItemType="Mace",ItemPrice=198.00M,ItemDescription="As with all lunar weapons, the lunar steel mace bears the Silent Moons Enchant. This unique enchantment burns the target up to 10-20 points of damage upon impact.Lunar weapons are the only weapons that can be disenchanted to learn the enchantment Silent Moons Enchant. ",ItemID=37,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Mace of Molag Ba",ItemType="Mace",ItemPrice=1257.00M,ItemDescription="The Mace is given to the Dragonborn after the completion of the Daedric quest, The House of Horrors. It is initially called the Rusty Mace and made to look like an offering, placed at Molag Bal's altar. (The Mace of Molag Bal! I give you its true power, mortal. When your enemies lie broken and bloody before you, know that I will be watching.―Molag Bal)",ItemID=38,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Nordic Mace",ItemType="Mace",ItemPrice=410.00M,ItemDescription="A Nordic Mace (as well as two Nordic War Axes, a Nordic Warhammer, and a Nordic Sword) can be obtained at any level (no matter how low) by traveling from Windhelm to Solstheim, locating Thirsk Mead Hall, and accepting/completing the quest The Chief of Thirsk Hall (the final battle against the Nords doesn't even require any necessary effort on the Dragonborn's part).",ItemID=39,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Akaviri Sword",ItemType="Sword",ItemPrice=300M,ItemDescription="This sword is carried by Dexion Evicus after he is rescued in Prophet. It can be pickpocketed if the Dragonborn has the Misdirection perk, or it can be obtained by reverse pickpocketing a weapon of higher damage onto Dexion and re-entering the area.",ItemID=40,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Bloodscyth",ItemType="Sword",ItemPrice=1859M,ItemDescription="The blade, along with Soulrender, was once wielded by the legendary pirate king, Haknir Death-Brand. Upon his death, he cursed the blades before they were buried with him in Gyldenhul Barrow on Solstheim.",ItemID=41,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Chillrend",ItemType="Sword",ItemPrice=1442M,ItemDescription="Chillrend appears similar to a standard glass sword, but the blade is pale blue instead of green, giving it the appearance of being covered in frost. While drawn, the blade emanates a vapor as if it were experiencing sublimation, and also makes a constant hissing noise, similar to dry ice.",ItemID=42,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Eduj",ItemType="Sword",ItemPrice=330M,ItemDescription="Old Nordic Stories say It was one of the Weapons that Kvenel the Tongue Favored when he fought in Battle[1]. The other weapon was the legendary war axe, Okin",ItemID=43,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Forsworn Sword",ItemType="Sword",ItemPrice=70M,ItemDescription="This crude weapon is fashioned from sharpened bones and teeth, bound together with leather and reeds.",ItemID=44,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Harkon's Sword",ItemType="Sword",ItemPrice=1472M,ItemDescription="Harkon's Sword is a unique sword that appears in The Elder Scrolls V: Dawnguard. It is similar in appearance to the Blades Sword but with a different guard, or tsuba. It also has a notably lower base damage than the regular Blades Sword, which has a base damage of 11. ",ItemID=45,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Nightingale Blade",ItemType="Sword",ItemPrice=1665M,ItemDescription="The Nightingale Blade is a leveled, unique, One-Handed weapon that appears in The Elder Scrolls V: Skyrim. It once belonged to the Nightingale and former Thieves Guild Guildmaster Gallus Desidenius.",ItemID=46,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Miraak's Sword",ItemType="Sword",ItemPrice=427M,ItemDescription="Miraak's Sword is a unique, leveled One-Handed sword found in The Elder Scrolls V: Dragonborn. It has the second lightest weight and the highest base damage of any one-handed sword available, more powerful than both Chillrend and the Dragonbone Sword by one point. When the weapon is swung, the blade takes the shape of a tentacle and appears to grow in length, however this effect is purely cosmetic and does not appear when the weapon runs out of charge. Regardless if charged or not, the tentacles on the sword will constantly writhe around the blade, while it glitters in a dampened green shine. An orange/green eye is found at the base, near the hilt.",ItemID=47,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="The Pale Blade",ItemType="Sword",ItemPrice=914M,ItemDescription="Choosing to place The Pale Blade on the pedestal nearby will appease The Pale Lady and she will leave. However, picking up The Pale Blade again will cause her to reappear. In order to keep the weapon, The Pale Lady must be defeated.",ItemID=48,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Red Eagle's Bane",ItemType="Sword",ItemPrice=100M,ItemDescription="This sword once belonged to the legendary Reachman known as Red Eagle who is said to have existed around 1E 1030 [1]. Ancient tales say that when Hestra, Empress of Cyrodiil attempted an invasion of The Reach, he used this very sword to slaughter thousands of her soldiers before being killed himself . According to legend, he presented this sword to his people, and swore an oath: Fight on, and when at last the Reach is free, his blade should be returned to his tomb so that he might rise and lead them again.",ItemID=49,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Ghorbash’s Ancestral Axe",ItemType="War Axe",ItemPrice=30M,ItemDescription="Ghorbash’s Ancestral Axe is a one-handed axe in The Elder Scrolls V: Skyrim. It was supposed to be obtainable during a radiant quest given by potential follower/marriage prospect Ghorbash the Iron Hand in Dushnikh Yal, but was cut from the game. ",ItemID=50,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Hoarfrost",ItemType="War Axe",ItemPrice=941M,ItemDescription="Hoarfrost is a unique Ancient Nordic Pickaxe",ItemID=51,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Stalhrim War Axe",ItemType="War Axe",ItemPrice=1180M,ItemDescription="The Frost Damage enchantment is 25% stronger when placed on items crafted from Stalhrim. This effect is identical to the Frost Enchanter perk from the Enchanting skill tree, or the Augmented Frost perk from the Destruction skill tree.",ItemID=52,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Ceremonial Ax",ItemType="War Axe",ItemPrice=5M,ItemDescription="It is a replica of the legendary war axe, Okin, and it serves as a key to the tomb of Kvenel the Tongue when used alongside the Ceremonial Sword.",ItemID=53,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Okin",ItemType="War Axe",ItemPrice=150M,ItemDescription="Old Nordic stories say it was one of the weapons that Kvenel the Tongue favored when he fought in battle.[1] The other weapon was the legendary sword, Eduj.",ItemID=54,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dawnguard Rune Axe",ItemType="War Axe",ItemPrice=175M,ItemDescription="An axe imbued with magic fueled by the destruction of the unholy. With every victorious blow against an undead creature, its power grows. Arkay warns it's baneful charge abates with each dawn. Something to keep in mind, I suppose",ItemID=55,ItemClass=Item.ItemClassType.Weapon},
            new Item{ItemName="Dragonbone Battleaxe",ItemType="Battleaxe",ItemPrice=3000M,ItemDescription="Can be randomly obtained in Skyrim or obtained by defeating the Keepers in the Soul Cairn and then looting the remains. It can also be created at a forge. It is also a possible weapon of a summoned Wrathman, though it is not lootable",ItemID=56,ItemClass=Item.ItemClassType.Weapon},
        
            };


            items.ForEach(s => context.Items.Add(s));
            context.SaveChanges();
        }
    }
}